### PR TITLE
Uml diagrams refactor

### LINKED ISSUE #256: Update puml and png files to current project scope
- Person -> Student.
- AddressBook -> Teacher's Pet.

### PR DESCRIPTION
**Pull request by gnahzeus**
Closes #256

### CODE REVIEW

**Review by Echomo-Xinyu — COMMENTED** [review]
There exists the issue with duplicate arrow and non-existent field in `ModelClassDiagram.puml` and its png file. I have fixed it in the previous commit.

@seanflyyy I think you should add the `UniqueScheduleList` and its relevant fields into `ModelClassDiagram.puml`.

ps: just checkout to the branch and commit accordingly.

**Comment by gnahzeus** [comment]
Thanks @Echomo-Xinyu for the inputs! @seanflyyy Feel free to merge the PR once you've made the relevant changes.

**Comment by Echomo-Xinyu** [comment]
> Thanks @Echomo-Xinyu for the inputs! @seanflyyy Feel free to merge the PR once you've made the relevant changes.

I think we can merge this PR first so that we can avoid potential resolve conflict for others who may edit the diagram. @seanflyyy can update the schedule list later i guess.

**Review by Echomo-Xinyu — APPROVED** [review]
LGTM!

**Comment by seanflyyy** [comment]
> There exists the issue with duplicate arrow and non-existent field in `ModelClassDiagram.puml` and its png file. I have fixed it in the previous commit.
> 
> @seanflyyy I think you should add the `UniqueScheduleList` and its relevant fields into `ModelClassDiagram.puml`.
> 
> ps: just checkout to the branch and commit accordingly.

Sounds good!

**Pull request merged**
