### PR TITLE
Fix error in duplicate multiple deletes

### LINKED ISSUE #244: [PE-D][Tester D] Entering repeated indices in the `delete` command leads to unexpected behavior.
To reproduce, add 3 students to the student list, and run `delete 2 2`, it would reject the command, but still delete student 2 and student 3 from the list. Furthermore, the statistics would still reflect the original number of students.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ngxingyu/ped#2

### PR DESCRIPTION
**Pull request by gnahzeus**
Closes #244

Delete multiple duplicate indexes now return this user feedback:

Screenshot 2022-10-31 at 12 59 15 PM

Returns error in this order:
1. Duplicate index
2. Invalid index (index given <= 0)
3. Index out of bounds of index list (index given > length of list)

Screenshot 2022-10-31 at 1 00 22 PM
Screenshot 2022-10-31 at 1 00 37 PM

### CODE REVIEW

**Comment by seanflyyy** [comment]
@gnahzeus I don't think it makes sense to have a separate check for 0 1 1 and 1 1 0, I think it makes more sense to process from left to right, so 0 1 1 would be invalid index and 1 1 0 would be duplicate index.

**Comment by Echomo-Xinyu** [comment]
> @gnahzeus For 0 1 1 and 1 1 0, I think it makes more sense to process from left to right, so 0 1 1 would be invalid index and 1 1 0 would be duplicate index.

I agree with @seanflyyy's point as well. It makes more sense to process the index from left to right, instead of universally throwing the error of duplicate indexes first.

**Comment by gnahzeus** [comment]
Based on further discussion, the error will be ordered by severity.

Specifically:

1. Invalid index (index given <= 0)
2. Duplicate indexes
3. Index out of bounds of index list (index given > length of list)

**Comment by Echomo-Xinyu** [comment]
> Based on further discussion, the error will be ordered by severity.
> 
> Specifically:
> 
> 1. Invalid index (index given <= 0)
> 2. Duplicate indexes
> 3. Index out of bounds of index list (index given > length of list)

I have better understood the rationale of throwing duplicate indexes issue for the above example and agree with the current error message logic sequence. Good job!

**Review by Echomo-Xinyu — APPROVED** [review]
Well-examined logic! I think it would be better if you can add a test case for the duplicate index situation!

**Pull request merged**
